"""create initial tables

Revision ID: 4aa11878582d
Revises: 
Create Date: 2026-09-28 11:28:55.836567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa11878582d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=255), nullable=False),
    sa.Column('l_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AUCTIONEER', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='application_status'), nullable=False),
    sa.Column('business_name', sa.String(length=30), nullable=False),
    sa.Column('business_address', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_status', sa.Enum('ACTIVE', 'PENDING', 'INACTIVE', name='membership_status'), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cred', sa.Enum('NIN', 'BVN', name='cred_type'), nullable=False),
    sa.Column('hmac_vale', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cred')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.String(length=25), nullable=False),
    sa.Column('type', sa.Enum('NIN', 'BVN', name='document_type'), nullable=False),
    sa.Column('submitted_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('user_identity')
    op.drop_table('memberships')
    op.drop_table('applications')
    op.drop_table('users')
    # ### end Alembic commands ###
